import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarLayout from "./_components/layout/navbar";
import FooterLayout from "./_components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NavbarLayout />
                {children}
                <FooterLayout />
            </body>
        </html>
    );
}
